services:
  postgres:
    image: postgres:18
    container_name: legacy_postgres
    environment:
      POSTGRES_DB: legacy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

  otel-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: legacy_otel_lgtm
    environment:
      # ENABLE_LOGS_LOKI: true
      # ENABLE_LOGS_TEMPO: true
      ENABLE_LOGS_OTELCOL: true
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    restart: unless-stopped

volumes:
  postgres_data:
